import type { Metadata } from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "next-themes";
import Navbar from "@/components/navbar";
import React from "react";

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  generator: 'v0.dev'
};

export default function RootLayout({children} : { children: React.ReactNode; }) {
  return (
    <html lang="fr" suppressHydrationWarning>
        <body className={inter.className}>
            <ThemeProvider attribute="class" defaultTheme="light" enableSystem disableTransitionOnChange storageKey="math-viz-theme">
                <Navbar />
                {children}
            </ThemeProvider>
        </body>
    </html>
  );
}

